name: CI & CD

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]

env:
  SPRING_PROFILES_ACTIVE: ci

jobs:
  # CI
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: clone parent repository
        uses: actions/checkout@v3
        with:
          repository: torrency/torrency
          token: ${{ secrets.CLONE_TOKEN }}
          submodules: true

      - name: Setup Java JDK
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: zulu

      - name: Restore Build Cache
        uses: actions/cache@v3
        with:
          key: v1-jws-${{ hashFiles('jws/pom.xml') }}
          path: ~/.m2/repository

      - name: Full Test With Maven
        run: mvn --no-transfer-progress clean -Dskip.surefire.tests=false -D=skip.failsafe.tests=false package
        working-directory: jws
